services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    working_dir: /var/www/laravel
    volumes:
      - ./laravel:/var/www/laravel
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_DATABASE=games_catalogo
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
    # command: ["php", "artisan", "serve", "--host=0.0.0.0", "--port=8000"]
  db:
    image: postgres:11
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: games_catalogo
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
